# Generated by Django 5.1.6 on 2025-02-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('users', '0004_staff_username_shopowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='store',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='store.store'),
            preserve_default=False,
        ),
    ]
