# Generated by Django 5.1.6 on 2025-03-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_staff_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('staff', 'Staff'), ('shopowner', 'ShopOwner')], default='client', max_length=10),
        ),
    ]
