# Generated by Django 5.1.6 on 2025-02-19 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_client_order_directorder_onlineorder_product_order'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_order',
            name='client',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='users.client'),
            preserve_default=False,
        ),
    ]
