# Generated by Django 5.1.6 on 2025-02-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_client_order_client'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_order',
            name='product',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
            preserve_default=False,
        ),
    ]
