# Generated by Django 5.1.6 on 2025-02-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_product_order_product'),
        ('store', '0001_initial'),
        ('users', '0004_staff_username_shopowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_order',
            name='order',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directorder',
            name='store',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='store.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='staff_in_charge',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='users.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_order',
            name='order',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
            preserve_default=False,
        ),
    ]
