# Generated by Django 5.1.6 on 2025-02-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_client_order_order_directorder_store_and_more'),
        ('products', '0002_product_category'),
        ('users', '0005_staff_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='payment_status',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='shippong_address',
            field=models.TextField(default=-1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='status',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='client_order',
            constraint=models.UniqueConstraint(fields=('client', 'order'), name='unique_client_order'),
        ),
        migrations.AddConstraint(
            model_name='product_order',
            constraint=models.UniqueConstraint(fields=('product', 'order'), name='unique_product_order'),
        ),
    ]
