# Generated by Django 5.1.6 on 2025-03-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_onlineorder_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorder',
            name='store',
        ),
        migrations.DeleteModel(
            name='OnlineOrder',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='order',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='product',
        ),
        migrations.DeleteModel(
            name='DirectOrder',
        ),
        migrations.DeleteModel(
            name='Product_Order',
        ),
    ]
