# Generated by Django 5.1.6 on 2025-03-30 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_directorder_store_delete_onlineorder_and_more'),
        ('products', '0008_product_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVariant_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('phonevariant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.phonevariant')),
            ],
            options={
                'db_table': 'phonevariant_order',
                'constraints': [models.UniqueConstraint(fields=('phonevariant', 'order'), name='unique_phonevariant_order')],
            },
        ),
    ]
