# Generated by Django 5.1.6 on 2025-03-30 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_phonevariant_order'),
        ('users', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='staff_in_charge',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='users.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(default='tai', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='Invoices/'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
