# Generated by Django 5.1.6 on 2025-03-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_staff_in_charge_order_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client_Order',
        ),
    ]
