# Generated by Django 5.1.6 on 2025-02-19 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stock_quantity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('screen', models.TextField(blank=True)),
                ('cpu', models.TextField(blank=True)),
                ('rom', models.TextField(blank=True)),
                ('ram', models.TextField(blank=True)),
                ('front_camera', models.TextField(blank=True)),
                ('back_cammera', models.TextField(blank=True)),
                ('battery', models.TextField(blank=True)),
                ('charger', models.TextField(blank=True)),
                ('speaker', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'phone',
            },
            bases=('products.product',),
        ),
    ]
