# Generated by Django 5.1.6 on 2025-02-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=20)),
                ('rom', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'phone_configuration',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.CreateModel(
            name='PhoneVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('sold_quantity', models.IntegerField(default=0)),
                ('img', models.ImageField(default='fallback.png', upload_to='')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.phoneconfiguration')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.phone')),
            ],
            options={
                'db_table': 'phone_variant',
                'unique_together': {('phone', 'configuration', 'color')},
            },
        ),
    ]
