# Generated by Django 5.1.6 on 2025-02-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_phoneconfiguration_remove_product_img_url_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phoneconfiguration',
            unique_together={('ram', 'rom')},
        ),
    ]
