# Generated by Django 5.1.6 on 2025-02-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_phoneconfiguration_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='back_cammera',
            new_name='back_camera',
        ),
    ]
