# Generated by Django 5.1.6 on 2025-03-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_back_cammera_phone_back_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_link',
            field=models.CharField(blank=True, default='TOT40aILhxo', max_length=100),
        ),
    ]
