# Generated by Django 5.1.6 on 2025-02-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart_product',
            table='cart_product',
        ),
    ]
