# Generated by Django 5.1.6 on 2025-02-19 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_product_table'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='client_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
    ]
