# Generated by Django 5.1.6 on 2025-02-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='client_id',
            new_name='client',
        ),
    ]
