# Generated by Django 5.1.6 on 2025-02-19 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_product',
            name='cart',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
            preserve_default=False,
        ),
    ]
