# Generated by Django 5.1.6 on 2025-02-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cart_product_product'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart_product',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_cart_product'),
        ),
    ]
