# Generated by Django 5.1.6 on 2025-03-06 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cart_product_unique_cart_product'),
        ('products', '0007_rename_back_cammera_phone_back_camera'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_Product',
            new_name='Cart_PhoneVariant',
        ),
        migrations.RemoveConstraint(
            model_name='cart_phonevariant',
            name='unique_cart_product',
        ),
        migrations.RemoveField(
            model_name='cart_phonevariant',
            name='product',
        ),
        migrations.AddField(
            model_name='cart_phonevariant',
            name='phone_variant',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='products.phonevariant'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='cart_phonevariant',
            constraint=models.UniqueConstraint(fields=('cart', 'phone_variant'), name='unique_cart_variant'),
        ),
        migrations.AlterModelTable(
            name='cart_phonevariant',
            table='cart_phone_variant',
        ),
    ]
